CREATE SCHEMA IF NOT EXISTS news_service_schema;

create table comments
(id bigint primary key generated by default as identity,
 comment varchar(255),
  news_id bigint,
   user_id bigint);


create table news (
id bigint primary key generated by default as identity,
 create_at timestamp(6),
  description varchar(255),
   header varchar(255),
    news_category_id bigint,
     user_id bigint);

create table news_categories (
id bigint primary key generated by default as identity,
 category varchar(255) not null);

create table users (
id bigint primary key generated by default as identity,
 name varchar(255),
  surname varchar(255));